### ISSUE TITLE
Finalize Tag Line

### ISSUE THREAD

**Issue by digitaltopo** [Aria-experience/aria#5]
We need to come up with a short tag line for the project. 
**Please post ideas in comments!**

- [x] Brainstorm tag lines in comments
- [ ] Choose tag line
- [ ] Update website to use tagline
- [ ] Update github repo and readme with new tagline

**Comment by mardb** [comment]
Aria - A Universe of Wonder

**Comment by digitaltopo** [comment]
Aria: Hear your data, feel your Earth

**Comment by melugas** [comment]
- Your Universe, Your Sound
- Experience Planetary Sound 
- Harmonize with the Earth
- Harmony of the Universe
- Visceral Tones/Sounds of the Earth
-The Earth has a Voice. Take a listen. 
-The Earth's Harmonious Sounds at Your Fingertips
- The Earth is Alive. Interact with it as a being (quote from my Buddhist aunt who does sound ceremonies with the earth in Peru, btw.)
- Activate your Wonder. Feel Your Universe.

**Comment by jentoobento** [comment]
your universe in sound

**Comment by jentoobento** [comment]
play, feel, wonder

**Comment by melugas** [comment]
Aria: Our universe synthesized through touch and sound

**Comment by mardb** [comment]
Aria - A Universe of Wonder
or 
Aria - Exploring a Universe of Wonder
or
Aria- Unbounded exploration 

Aria - Freedom to Explore
Aria - The universe is your canvas 
Aria - exploring creativity
Aria - Exploring Nature’s creativity
Aria- Coloring the universe

**Comment by digitaltopo** [comment]
Thanks everyone for brainstorming! My 0.02c:

- Most of these taglines are "marketing" taglines, which i think is great, but if we go with one of them, we should also make sure we add in a line that is more descriptive of the project for hackathon purposes, like we had in the presentation: "Algorithmically generated music for Earth Observation data" or something to that effect that actually is a simple, easy, one line sentence that describes and communicates what our project actually does. Maybe we can call this the "subtitle" because it's nice to have a cool tagline as well.
- I get that at some point the idea started around astronomy data and hubble images of the universe, but so far that's not what we have, so doesn't make much sense to me to go with something that talks about the universe. We need to be compact and clear so our project isn't confusing. Can we please stick to "earth" for now, and do universe after the hackathon?

**Comment by mardb** [comment]
I would really like to see it be about "universe" just so that we can describe it and the actual animated logo zooms from earth into space. Its not about what the idea "started" with. I think its more about being limitless. unbounded. I think this is something I gave my opinion on. Im open to what ever the rest of the team has to say. I think we can be compact and clear and its not confusing especially if we are adding Melissa's voice over to the video. Can you be more open about this specific topic? Jennifer and Melissa, what do you all have to say about this? 

-Marlene
    On Friday, October 26, 2018, 7:30:09 PM PDT, Orestis Herodotou <notifications@github.com> wrote:  
 
 
Thanks everyone for brainstorming! My 0.02c:
   
   - Most of these taglines are "marketing" taglines, which i think is great, but if we go with one of them, we should also make sure we add in a line that is more descriptive of the project for hackathon purposes, like we had in the presentation: "Algorithmically generated music for Earth Observation data" or something to that effect that actually is a simple, easy, one line sentence that describes and communicates what our project actually does. Maybe we can call this the "subtitle" because it's nice to have a cool tagline as well.
   - I get that at some point the idea started around astronomy data and hubble images of the universe, but so far that's not what we have, so doesn't make much sense to me to go with something that talks about the universe. We need to be compact and clear so our project isn't confusing. Can we please stick to "earth" for now, and do universe after the hackathon?

**Comment by jentoobento** [comment]
i like universe but itshould have subtitle too

**Comment by digitaltopo** [comment]
I strongly feel that talking about the universe when the whole thing is a map of earth is confusing. Literally everything we have is earth based. The earth observation data concept is really powerful and proven to be something judges like, we should work off of that now, that is what the project is. What we have is AWESOME, why do we need to change it to something we don't have?? It would make so much more sense to just stick with Earth. It's not that we can't voice over and explain etc, the point is the best thing would not NEED an explanation or correction. 

```
Aria: A Universe of Wonder.... (huh?)
Algorithmically generated music for Earth Observation data

What does your app do? 
Works with NASA GIBS datasets of the earth

How do you do that?
You get to create music from a map of the earth.
```

I think that we have a lot of strong ones that don't need explanation, just as an example: 

**"The Earth has a Voice. Take a listen." **

This one is really engaging. It has an action for the reader, a next step. It empowers the earth (giving it a voice) which is so important right now, and it's related to the title, Aria, which is a word about sound and music.

**Comment by mardb** [comment]
Do what ever you feel is best Orestis.  
    On Friday, October 26, 2018, 7:56:49 PM PDT, Orestis Herodotou <notifications@github.com> wrote:  
 
 
I strongly feel that talking about the universe when the whole thing is a map of earth is confusing. Literally everything we have is earth based. The earth observation data concept is really powerful and proven to be something judges like, we should work off of that now, that is what the project is. What we have is AWESOME, why do we need to change it to something we don't have?? It would make so much more sense to just stick with Earth. It's not that we can't voice over and explain etc, the point is the best thing would not NEED an explanation or correction.
Aria: A Universe of Wonder.... (huh?)
Algorithmically generated music for Earth Observation data

What does your app do? 
Works with NASA GIBS datasets of the earth

How do you do that?
You get to create music from a map of the earth.

I think that we have a lot of strong ones that don't need explanation, just as an example:

**"The Earth has a Voice. Take a listen." **

This one is really engaging. It has an action for the reader, a next step. It empowers the earth (giving it a voice) which is so important right now, and it's related to the title, Aria, which is a word about sound and music.

**Comment by melugas** [comment]
1. Hear Your Earth. Activate Your Senses. 
2. The Earth has a Voice. Take A Listen. 
3. Aria: Unbounded Earth Exploration

**Comment by jentoobento** [comment]
universe of wonder
activare your wonder feel your universe
exploring a universe of wonder

**Comment by melugas** [comment]
Guys I was about to update our team page on the space apps site and saw that "universe of beauty and wonder" was a challenge prompt - perhaps consider shelving that one for now until we're not associated with them anymore?

**Comment by mardb** [comment]
unbounded Exploration
activare your wonder feel your universe
exploring a universe of wonder

**Comment by digitaltopo** [comment]
Sent out the vote! Check your emails

**Comment by digitaltopo** [comment]
![aria-tagline](https://user-images.githubusercontent.com/1680796/47608753-7c3f5c00-d9e7-11e8-9160-e9a7ac30de4b.png)
